-- Opcional: Limpar a tabela antes de criar (útil para o ambiente de tutorial)
DROP TABLE IF EXISTS movies;

CREATE TABLE movies (
    -- 'id' usando a sintaxe nativa do Postgres para auto-incremento
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    genre VARCHAR(100) NOT NULL,
    release_date DATE,
    rating NUMERIC(3, 1), -- Melhor que DOUBLE para notas como 8.8
    description TEXT,

    CONSTRAINT pk_movie PRIMARY KEY (id)
);

INSERT INTO movies (title, genre, release_date, rating, description) VALUES
('O Poderoso Chefão', 'Crime/Drama', '1972-03-24', 9.2, 'O patriarca envelhecido de uma dinastia do crime organizado transfere o controle de seu império clandestino para seu filho relutante.'),
('Interestelar', 'Ficção Científica/Drama', '2014-11-06', 8.7, 'Uma equipe de exploradores viaja através de um buraco de minhoca no espaço na tentativa de garantir a sobrevivência da humanidade.'),
('Batman: O Cavaleiro das Trevas', 'Ação/Crime', '2008-07-18', 9.0, 'Quando a ameaça conhecida como o Coringa surge de seu passado, ele causa estragos e caos no povo de Gotham.'),
('Matrix', 'Ficção Científica/Ação', '1999-03-31', 8.7, 'Um hacker aprende com rebeldes misteriosos sobre a verdadeira natureza de sua realidade e seu papel na guerra contra seus controladores.'),
('O Senhor dos Anéis: O Retorno do Rei', 'Fantasia/Aventura', '2003-12-17', 9.0, 'Gandalf e Aragorn lideram o Mundo dos Homens contra o exército de Sauron para desviar o olhar do Um Anel enquanto Frodo e Sam se aproximam da Montanha da Perdição.');